# Generated by Django 4.0.4 on 2022-09-10 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Aditya Kanodia', max_length=20)),
                ('position', models.CharField(default='', max_length=25)),
                ('img', models.ImageField(default='images/img.jpeg', upload_to='images')),
                ('zipcode', models.IntegerField(default=100000)),
                ('address', models.TextField(default='')),
                ('phone', models.CharField(default='', max_length=15)),
                ('email', models.EmailField(default='adityakanodia08@gmail.com', max_length=254)),
                ('github', models.URLField(default='')),
                ('linkedin', models.URLField(default='')),
                ('twitter', models.URLField(default='')),
            ],
        ),
    ]
