# Generated by Django 4.0.4 on 2022-09-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='img',
            field=models.ImageField(default='images/img.webp', upload_to='images'),
        ),
    ]
